import { StrictMode, useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Terminal } from '@xterm/xterm';
import { FitAddon } from '@xterm/addon-fit';
import '@xterm/xterm/css/xterm.css';
import { AppHostClient } from './host-api';
import './style.css';

type Profile = { id: string; name: string; host: string; port: number; username: string; auth: 'password' | 'privateKey'; privateKeyPath?: string; credentialId?: string; hostKey?: string; };
const host = new AppHostClient();
function App() { const [profiles, setProfiles] = useState<Profile[]>([]); const [active, setActive] = useState<string>(); const [form, setForm] = useState<Profile>({ id: '', name: '', host: '', port: 22, username: '', auth: 'password' }); const terminalRef = useRef<HTMLDivElement>(null); const term = useRef<Terminal | null>(null); const session = useRef<string | null>(null);
  const refresh = () => host.invoke<Profile[]>('profiles.list').then(setProfiles); useEffect(() => { void refresh(); }, []);
  useEffect(() => { if (!terminalRef.current || term.current) return; const terminal = new Terminal({ cursorBlink: true, theme: { background: '#10161d', foreground: '#d7f5df' } }); const fit = new FitAddon(); terminal.loadAddon(fit); terminal.open(terminalRef.current); fit.fit(); terminal.onData((data) => { if (session.current) void host.invoke('sessions.input', { id: session.current, data }); }); term.current = terminal; return host.onEvent((event) => { const value = event.payload as { id?: string; data?: string; title?: string; message?: string; fingerprint?: string; profile?: Profile }; if (event.event === 'session.data' && value.id === session.current) terminal.write(value.data ?? ''); if (event.event === 'session.ready' && value.id) { session.current = value.id; setActive(value.id); terminal.writeln(`\r\n已连接：${value.title ?? ''}\r\n`); } if (event.event === 'session.host-key' && value.profile && value.fingerprint && confirm(`首次连接 ${value.profile.host}。确认主机密钥指纹：\n${value.fingerprint}`)) void connect({ ...value.profile, hostKey: value.fingerprint }); if (event.event === 'session.error') terminal.writeln(`\r\n错误：${value.message ?? ''}\r\n`); }); }, []);
  const connect = async (profile: Profile, secret?: string) => { const credentialId = profile.credentialId || crypto.randomUUID(); if (secret) await host.invoke('ssh.credentials.write', { credentialId, secret }); const saved = await host.invoke<Profile>('profiles.save', { ...profile, credentialId }); await refresh(); await host.invoke('sessions.connect', { profile: saved, secret: secret || await host.invoke('ssh.credentials.read', { credentialId }) }); };
  return <main><header><strong>SSH 终端</strong><span>最近连接</span>{profiles.slice(0, 3).map((profile) => <button key={profile.id} onClick={() => { const secret = prompt(`输入 ${profile.name || profile.host} 的密码或私钥口令（留空则使用已保存凭据）`) || undefined; void connect(profile, secret); }}>{profile.name || profile.host}</button>)}<button onClick={() => setForm({ id: '', name: '', host: '', port: 22, username: '', auth: 'password' })}>管理连接</button></header><section className="body"><aside><h2>已保存连接</h2>{profiles.map((profile) => <button className="profile" key={profile.id} onClick={() => setForm(profile)}>{profile.name || profile.host}<small>{profile.username}@{profile.host}</small></button>)}<form onSubmit={(event) => { event.preventDefault(); const secret = prompt('输入密码或私钥口令（留空则不更新已保存凭据）') || undefined; void connect(form, secret); }}><h2>{form.id ? '编辑连接' : '新建连接'}</h2>{(['name', 'host', 'username', 'privateKeyPath'] as const).map((key) => key === 'privateKeyPath' && form.auth !== 'privateKey' ? null : <input key={key} placeholder={key === 'privateKeyPath' ? '私钥文件路径' : key === 'name' ? '名称' : key === 'host' ? '主机地址' : '用户名'} value={form[key] ?? ''} onChange={(event) => setForm({ ...form, [key]: event.target.value })} />)}<input type="number" value={form.port} onChange={(event) => setForm({ ...form, port: Number(event.target.value) })} /><select value={form.auth} onChange={(event) => setForm({ ...form, auth: event.target.value as Profile['auth'] })}><option value="password">密码</option><option value="privateKey">私钥</option></select><button type="submit">保存并连接</button></form></aside><section className="terminal"><div className="tabs">{active ? '已连接终端' : '尚未连接'}</div><div ref={terminalRef} className="terminal-screen" /></section></section></main>; }
createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>);
